# Generated by Django 4.2 on 2023-06-16 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_expense_product_id_expense_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='arrival_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='№ Прихода'),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='products',
            field=models.ManyToManyField(to='main.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='№ Покупателя'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='№ Расхода'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='products',
            field=models.ManyToManyField(to='main.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='№ Товара'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^((\\+\\d{,4})[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='№ Продавца'),
        ),
    ]
