# Generated by Django 3.2.9 on 2023-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='image/%M', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
