# Generated by Django 3.2.9 on 2023-04-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='pos',
            new_name='art',
        ),
    ]
