# Generated by Django 3.2.9 on 2023-04-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_commentlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='art',
            new_name='com',
        ),
    ]
