# Generated by Django 3.2.9 on 2023-04-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='nickname',
        ),
    ]
