# Generated by Django 3.2.9 on 2023-04-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_pos_like_art'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='ArticleLike',
        ),
    ]
