# Generated by Django 4.2 on 2023-05-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_productarrivals_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.TextField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
