# Generated by Django 4.2 on 2023-05-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.TextField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
