# Generated by Django 4.2 on 2023-05-16 09:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrival',
            options={'ordering': ['arrival_id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_id']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['expense_id']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['supplier_id']},
        ),
        migrations.AlterField(
            model_name='arrival',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supplier', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(max_length=255, verbose_name='Имя контакта'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название контакта'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Номер телефона'),
        ),
    ]
