# Generated by Django 4.2 on 2023-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_arrival_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='product_id',
        ),
        migrations.AddField(
            model_name='arrival',
            name='products',
            field=models.ManyToManyField(to='main.product'),
        ),
    ]
