# Generated by Django 4.2 on 2023-05-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_arrival_product_id_arrival_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='product_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='products',
            field=models.ManyToManyField(to='main.product', verbose_name='Информация о товаре'),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='products',
            field=models.ManyToManyField(to='main.product', verbose_name='Информация о товаре'),
        ),
    ]
