# Generated by Django 4.2.4 on 2023-08-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
                ('date_start', models.DateField(verbose_name='Дата выхода')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre', verbose_name='Жанр')),
            ],
        ),
    ]
