# Generated by Django 4.2.4 on 2023-09-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_serial_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год выхода'),
        ),
    ]
