version: '3.11'

services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  django:
    build: .
    command:
      - python /usr/src/kwork/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/kwork
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres_data:
